server:
  port: 8080

eureka:
  client:
    register-with-eureka: false

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: task
          uri: lb://msvc-task
          predicates:
            - Path=/task/**
        - id: user
          uri: lb://msvc-user
          predicates:
            - Path=/user/**

