server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: msvc-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: task
          uri: lb://msvc-task
          predicates:
            - Path=/task/**
        - id: user
          uri: lb://msvc-user
          predicates:
            - Path=/user/**

